# Generated by Django 3.1.4 on 2023-03-19 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis', models.IntegerField(blank=True, null=True)),
                ('sh', models.IntegerField(blank=True, null=True)),
                ('way', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverAPI.route')),
            ],
        ),
    ]
